### PR TITLE
FIX: loop to get all the repository names

### LINKED ISSUE #93: Purge with repository filter may miss some repos
**Describe the bug**
Recently added repository filter is awesome. However, the filter may miss some repositories because `GetRepositories` only returns the first 100 repos by default. If your registry contains more than 100 repos, the purge cmd would work incorrectly.

**To Reproduce**
1. Choose a container registry with more than 100 repositories.
2. Use `acr purge` with repository filter such as `--filter ".*:.*"`

**Expected behavior**
All the repositories should be purged.

**Additional context**
A workaround is to set a large `int32` like 10,000 as the parameter `n` of function `GetRepositories`, which is really ugly... Any suggestions?

### PR DESCRIPTION
**Pull request by shudiwsh2009**
**Purpose of the PR**

- Loop to get all the repository names for later regexp filter

Fixes #93

### CODE REVIEW

**Review by northtyphoon — APPROVED** [review]
LGTM. Thanks for fixing the bug.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by Wwwsylvia — APPROVED** [review]
LGTM

**Comment by Wwwsylvia** [comment]
The PR is now merged. Thanks @shudiwsh2009  for the contribution!

**Pull request merged**
